version: '3.5'

networks: 
  inside_net:
    name: inside_net
    driver: bridge

services:
  nginx_proxy:
    image: nginx:1.25.2
    container_name: nginx_proxy
    restart: always
    ports: 
      - '${APP_PROXY_PORT}:${APP_PROXY_PORT}'
    environment: 
      - 'APP_PROXY_PORT=${APP_PROXY_PORT}'
      - 'APP_PROXY_HOST=${APP_PROXY_HOST}'
      - 'APP_HOST=app'
      - 'APP_PORT=${APP_PORT}'
      - 'ADMINER_HOST=adminer'
      - 'ADMINER_PORT=8080'
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./${FILE_STATIC_DIR_NAME}:/${FILE_STATIC_DIR_NAME}:ro
    depends_on:
      - app
      - adminer
    networks: 
      - inside_net

  app: 
    build: 
      context: ./
      dockerfile: ./docker/dev/dockerfile
    container_name: app
    restart: always
    environment: 
      - 'NODE_ENV=${NODE_ENV}'
      - 'APP_PROXY_HOST=${APP_PROXY_HOST}'
      - 'APP_PROXY_PORT=${APP_PROXY_PORT}'
      - 'APP_PORT=${APP_PORT}'
      - 'DB_HOST=postgres_db'
      - 'DB_PASSWORD=${DB_PASSWORD}'
    depends_on: 
      - postgres_db
    volumes:
      - ./${FILE_STATIC_DIR_NAME}:/usr/app/${FILE_STATIC_DIR_NAME}
    networks: 
      - inside_net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment: 
      - 'ADMINER_DEFAULT_SERVER=postgres_db:5432'
    networks: 
      - inside_net

  postgres_db: 
    image: postgres:16.0
    container_name: postgres_db
    restart: always
    environment: 
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
      - 'POSTGRES_DB=${DB_NAME}'
    volumes: 
      - ./postgres_data/${DB_NAME}.gz:/var/backups/${DB_NAME}.gz:ro
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./postgres_data:/var/lib/postgresql/data
    networks: 
      - inside_net
